---
kind: pipeline
type: docker
name: firmware

steps:
- name: build
  image: petewall/platformio
  commands:
  - cp hardware/firmware/include/credentials.example.h hardware/firmware/include/credentials.h
  - cd hardware/firmware && make

---
kind: pipeline
type: docker
name: backend

steps:
- name: build
  image: golang
  commands:
  - cd server && make

---
kind: pipeline
type: docker
name: frontend

steps:
- name: build
  image: gableroux/flutter:v1.9.1_hotfix.4
  commands:
  - cd app
  - flutter doctor
  - flutter build apk --release
  - flutter test