---
kind: pipeline
type: docker
name: firmware

steps:
  - name: fetch-submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: build
    image: petewall/platformio
    commands:
      - cp hardware/firmware/include/credentials.example.h hardware/firmware/include/credentials.h
      - cd hardware/firmware && make

# FIXME: The unit tests currently don't work on the desktop platform.
# They do however run on actual hardware, which of course is not testable in CI
#- name: test
#  image: petewall/platformio
#  commands:
#  - cd hardware/firmware && make test-desktop

---
kind: pipeline
type: docker
name: backend

steps:
  - name: build
    image: golang
    commands:
      - cd server && make

  - name: test
    image: golang
    commands:
      - cd server && make test
