# This workflow will run the flutter app's tests and build the APK

name: App
on:
  pull_request:
  push:
    paths:
      - app/**

jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '13.x'
      - name: Test and Build
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter test
        working-directory: ./app
  buildAPK:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '13.x'
      - name: Build
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter build apk
        working-directory: ./app
      # Attach the APK as an artifact to each build (so it can easily be viewed for each build)
      # We're using v2-preview of the action, since it allows to upload single files
      - name: Upload artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: app
          path: build/app/outputs/apk/app.apk
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: buildAPK
    steps:
      # If we pushed a tag, create a release and attach the paper to it
      # This will update the release, if it already exists
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: ${{ endsWith(github.ref, '-rc') || endsWith(github.ref, 'nightly') }}
      - name: Download artifact
        id: download_artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v2-preview
        with:
          name: app
      - name: Upload Release Asset
        id: upload-release-asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/app.apk
          asset_name: Paper-Tracker-${{ github.ref }}.apk
          asset_content_type: application/vnd.android.package-archive




