name: Backend
on:
  pull_request:
  push:
    paths:
      - server/**

jobs:
  test:
    name: Test for Go version ${{ matrix.golang }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.golang }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.golang }}
    - name: Get dependencies
      run: go get -v -t -d ./...
      working-directory: ./server
    - name: Test
      run: make test
      working-directory: ./server
    strategy:
      matrix:
        golang: [ '1.13', '1.14' ]

  build:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        working-directory: ./server
        run: make && mv paper-tracker paper-tracker_linux_x86_64
      - name: Upload artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: server
          path: server/paper-tracker*

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        id: download_artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v2-preview
        with:
          name: server
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1.6.1
        with:
          allowUpdates: true
          draft: false
          replaceArtifacts: false
          artifacts: 'server/paper-tracker*'
          prerelease: ${{ endsWith(github.ref, '-rc') || endsWith(github.ref, 'nightly') }}
          token: ${{ secrets.GITHUB_TOKEN }}

