# This workflow will build the flasher for windows and linux and attach it to releases
#
name: Flasher
on:
  pull_request:
  push:
    paths:
      - hardware/flasher/**

defaults:
  run:
    working-directory: hardware/flasher

jobs:
  build:
    name: Build flasher for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Pack zip
        run: make zip
      - name: Rename zip
        run: mv dist.zip flasher-${{ runner.os }}.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: flasher
          path: "flasher*.zip"
    strategy:
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest' ]

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        id: download_artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v2-preview
        with:
          name: flasher
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1.6.1
        with:
          allowUpdates: true
          tag_name: ${{ github.ref }}
          replacesArtifacts: false
          artifacts: "**/flasher*.zip"
          artifactContentType: "application/zip"
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, 'nightly') || contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          token: ${{ secrets.GITHUB_TOKEN }}

