# This workflow will build the paper

name: Paper
on:
  pull_request:
  push:
    paths:
      - paper/**

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@1.2.1
        with:
          working_directory: paper
          root_file: Studienarbeit.tex
          args: -interaction=nonstopmode -pdflatex=lualatex -lualatex -file-line-error -pdf -e "$max_repeat=10"
      - uses: actions/upload-artifact@v1
        with:
          name: Studienarbeit.pdf
          path: paper/Studienarbeit.pdf


