# This workflow will build the paper

name: Paper
on:
  pull_request:
  push:
    paths:
      - paper/**

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@1
        with:
          working_directory: paper
          root_file: Studienarbeit.tex
          args: -interaction=nonstopmode -pdflatex=lualatex -lualatex -file-line-error -pdf -e "$max_repeat=10"
      # Attach the paper as an artifact to each build (so it can easily be viewed for each build)
      # We're using v2-preview of the action, since it allows to upload single files
      - uses: actions/upload-artifact@v2-preview
        with:
          name: Studienarbeit.pdf
          path: paper/Studienarbeit.pdf


