# This workflow will build the paper

name: Paper
on:
  pull_request:
  push:
    paths:
      - paper/**

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@1
        with:
          working_directory: paper
          root_file: Studienarbeit.tex
          args: -interaction=nonstopmode -pdflatex=lualatex -lualatex -file-line-error -pdf -e "$max_repeat=10"
      # Attach the paper as an artifact to each build (so it can easily be viewed for each build)
      # We're using v2-preview of the action, since it allows to upload single files
      - name: Upload artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: paper
          path: paper/Studienarbeit.pdf

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: compile
    steps:
      # If we pushed a tag, create a release and attach the paper to it
      # This will update the release, if it already exists
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: ${{ endsWith(github.ref, '-rc') || endsWith(github.ref, 'nightly') }}
      - name: Download artifact
        id: download_artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v2-preview
        with:
          name: paper
      - name: Upload Release Asset
        id: upload-release-asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: paper/Studienarbeit.pdf
          asset_name: Paper.pdf
          asset_content_type: application/pdf


